{"name": "test_return_message", "status": "failed", "statusDetails": {"message": "AssertionError: 值为奇数,应为偶数\nassert 1 == 0\n  +1\n  -0", "trace": "def test_return_message():\n        a = 1\n>       assert a % 2 == 0, \"值为奇数,应为偶数\"\nE       AssertionError: 值为奇数,应为偶数\nE       assert 1 == 0\nE         +1\nE         -0\n\ntest_01_assert_for_allure.py:22: AssertionError"}, "start": 1627036707009, "stop": 1627036707009, "uuid": "74d8ab76-27a7-46ff-96a1-161ab1b714fa", "historyId": "f8689eb88b6e745724ed021e07d7ee0e", "testCaseId": "e6bfb4e7eb4cb88ecbf0234f39703e80", "fullName": "test_01_assert_for_allure#test_return_message", "labels": [{"name": "suite", "value": "test_01_assert_for_allure"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "11292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01_assert_for_allure"}]}