{"name": "test_num[17]", "status": "failed", "statusDetails": {"message": "Failed: bad luck", "trace": "i = 17\n\n    @pytest.mark.parametrize(\"i\",range(50))\n    def test_num(i):\n        if i in (17,25):\n>          pytest.fail(\"bad luck\")\nE          Failed: bad luck\n\ntest_06_cache.py:19: Failed"}, "parameters": [{"name": "i", "value": "17"}], "start": 1627037560371, "stop": 1627037560371, "uuid": "1272ea8a-9c77-4430-b235-3d9c4db8388b", "historyId": "9d9793655b91929c904530406c7c8473", "testCaseId": "8183d3bbf7c705ec724fd563a7ea7118", "fullName": "test_06_cache#test_num", "labels": [{"name": "suite", "value": "test_06_cache"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "4280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_06_cache"}]}