{"name": "test_num[25]", "status": "failed", "statusDetails": {"message": "Failed: bad luck", "trace": "i = 25\n\n    @pytest.mark.parametrize(\"i\",range(30))\n    def test_num(i):\n        if i in (17,25,30):\n>          pytest.fail(\"bad luck\")\nE          Failed: bad luck\n\ntest_06_cache.py:19: Failed"}, "parameters": [{"name": "i", "value": "25"}], "start": 1627038709253, "stop": 1627038709253, "uuid": "fd04a748-a524-4f13-aa0c-5a19e35a2b34", "historyId": "c34926ed4dccbc96be647bf95f66f6f7", "testCaseId": "8183d3bbf7c705ec724fd563a7ea7118", "fullName": "test_06_cache#test_num", "labels": [{"name": "suite", "value": "test_06_cache"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "19824-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_06_cache"}]}