{"name": "test_num[17]", "status": "failed", "statusDetails": {"message": "Failed: bad luck", "trace": "i = 17\n\n    @pytest.mark.parametrize(\"i\",range(50))\n    def test_num(i):\n        if i in (17,25):\n>          pytest.fail(\"bad luck\")\nE          Failed: bad luck\n\ntest_06_cache.py:19: Failed"}, "parameters": [{"name": "i", "value": "17"}], "start": 1627038118099, "stop": 1627038118099, "uuid": "16e94b03-9a45-4c65-a04f-2cda1ad45c2c", "historyId": "9d9793655b91929c904530406c7c8473", "testCaseId": "8183d3bbf7c705ec724fd563a7ea7118", "fullName": "test_06_cache#test_num", "labels": [{"name": "suite", "value": "test_06_cache"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "18748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_06_cache"}]}