{"name": "test_num[25]", "status": "failed", "statusDetails": {"message": "Failed: bad luck", "trace": "i = 25\n\n    @pytest.mark.parametrize(\"i\",range(50))\n    def test_num(i):\n        if i in (17,25):\n>          pytest.fail(\"bad luck\")\nE          Failed: bad luck\n\ntest_06_cache.py:19: Failed"}, "parameters": [{"name": "i", "value": "25"}], "start": 1627037560486, "stop": 1627037560486, "uuid": "ec1d77e2-be66-4532-acbc-4aa0f96eb2d5", "historyId": "c34926ed4dccbc96be647bf95f66f6f7", "testCaseId": "8183d3bbf7c705ec724fd563a7ea7118", "fullName": "test_06_cache#test_num", "labels": [{"name": "suite", "value": "test_06_cache"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "4280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_06_cache"}]}