{"name": "test_return_message", "status": "failed", "statusDetails": {"message": "AssertionError: 值为奇数,应为偶数\nassert 1 == 0\n  +1\n  -0", "trace": "self = <test_demo.test_01_assert_for_allure.TestAllure object at 0x000001E1A8D66188>\n\n    @allure.testcase(\"case url\",\"test case: # 2. 指定断言失败返回信息\")\n    def test_return_message(self):\n        a = 1\n>       assert a % 2 == 0, \"值为奇数,应为偶数\"\nE       AssertionError: 值为奇数,应为偶数\nE       assert 1 == 0\nE         +1\nE         -0\n\ntest_01_assert_for_allure.py:25: AssertionError"}, "start": 1627038694027, "stop": 1627038694028, "uuid": "39407418-2a4c-4d2b-9a34-4a32b9eeaf3f", "historyId": "e614d4723b5c6f39330f48e56b740096", "testCaseId": "d4b43c4df81b97ea8689e52b0a8e7559", "fullName": "test_01_assert_for_allure.TestAllure#test_return_message", "labels": [{"name": "story", "value": "story: assert"}, {"name": "suite", "value": "test_01_assert_for_allure"}, {"name": "subSuite", "value": "TestAllure"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "19824-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01_assert_for_allure"}], "links": [{"type": "test_case", "url": "case url", "name": "test case: # 2. 指定断言失败返回信息"}]}